os: linux

# we use the R VM because it contains LaTeX and pandoc
language: r
cache: packages

# we need super user privileges, so we depend on the old travis-ci infrastructure
sudo: required

# we can install additional software
# apt_packages:
# we download pdf2djvu to also generate a djvu file of our LaTeX source
#  - pdf2djvu

warnings_are_errors: false

before_install:
# bash script which installs git lfs in travis deployment machine and pulls files 
  - ./travis/installGitLFS.sh
  - cd Ausbaustufe_1_Analyse
# installs openjdk for professorial chair watermark-removal-tool
  - sudo apt-get install -y openjdk-7-jre
  - sudo apt-get install -y texlive-lang-german
# LaTeX-packages which aren't included in the standard package 
  - tlmgr install babel
  - tlmgr install was

script:
# if you have a markdown source, you can use pandoc to convert it to a LaTeX document
#  - cat README.md | grep --invert-match "\[\!\[" > README2.md
#  - cat README2.md | grep --invert-match "Howto Deploy LaTeX Documents" > README.md
#  - pandoc -s --from=markdown_github --to=latex -M title="Howto Deploy LaTeX Documents" -M author="S$
#  - make

# in the next step we use pdflatex to convert .tex to .pdf
# of course we could use pandoc for this also, but pdflatex generates nicer PDFs
#  - pdflatex -interaction=nonstopmode HowtoDeployLatexDocs-DE.tex
#  - pdflatex -interaction=nonstopmode HowtoDeployLatexDocs-EN.tex
#  - pdflatex -interaction=nonstopmode README.tex
  - java -jar ../travis/remove-watermark-from-svg/deltrans.jar img/*.svg -pattern "Paradigm" -outformat pdf
  - java -cp ../travis ExitCodeManager

# now we convert the pdf file to a much smaller djvu document
#  - pdf2djvu -d 1200 -o HowtoDeployLatexDocs-DE.djvu HowtoDeployLatexDocs-DE.pdf
#  - pdf2djvu -d 1200 -o HowtoDeployLatexDocs-EN.djvu HowtoDeployLatexDocs-EN.pdf
after_success:
# upload the previously generated pdf file to simonwaldherr.de (use $UPLOADSECRET as password)
#  - wget --post-file=HowtoDeployLatexDocs-DE.pdf -q -O- "https://simonwaldherr.de/pdf/?repo=HowtoDep$

deploy:
  provider: releases
  file: "main.pdf"
  api_key:
    secure: gOgjpQN4xC9zBH0SY742Aa/mR1J7P+9wJl+4QR77SLpApjCFWY/M0oBnZxfuXWuo3arAjeMpPC/CAZEL0FYsjS4xqhqmFoMsKMiSBKASeX2CDGTy/LydERBlI/IgQQOk1eHTV2V0xfrwZulXEwdNZF7BXDCC5A2Ehz07PYk8Vlz7dQcR3PbPEuyVX0kyMCaYNJKy5Lad+AbJv8HFThFQuyrxsDsbDJPeQtQMMi6i5Z6e+rlMGyEWfm5zM5teAGhoUf17qn7+NAFi2nCeno2FB8nmwJv9AeJGVyaOvXDZxmtnoZvZr2cJXRh7xj5GBETqMP5VwtvnHsot9iZY8lGNdAsgHj267mqrNJs9IFfey3YoV3Vdzt1d59G0c+q3WsWYEwLAH2bcZZYHK9FnWZGiyJiJ5fVNIivJ3FUmWKaN/1tTyYsobZcW1DJyQL8hoHaCoBn+mzkAyZy3KpU9xpMG3doveqckRC1fhUvmdEmnVZOAD6JL8/fqC5D8TPGsruQSfNsUGwUZW+Har1NcWx9iqJ6WWnO39Zq9IwItpzl8qo6ttUgT8i93j17Ccwq7Qi0+1A8tGe5B6vrVvZ/Y5L4/osUf9PaLZdh0enz3aduoWgV88gjHXxAHOQ8Jmbmy8w0BoW8X1Ch37xsxu8iITrjilq0qbjyvypfioBUTLj6mvMU=
  on:
    repo: hpi-mod-fuenf/main
